name: Deploy
run-name: ${{github.actor}} is deploying googlepay test app 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} 
          heroku_app_name: googlepay-paypal-js-sdk # Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "advanced-integration"
          healthpeak: "https://googlepay-paypal-js-sdk.herokuapp.com/health"
          usedocker: true
          dontuseforce: false
          docker_build_args: |
            NODE_ENV
            PAYPAL_CLIENT_ID
            PAYPAL_CLIENT_SECRET
            PAYPAL_MERCHANT_ID
            BASE_URL
        env:
          NODE_ENV: ${{secrets.NODE_ENV}}
          PAYPAL_CLIENT_ID: ${{secrets.CLIENT_ID}}
          PAYPAL_CLIENT_SECRET: ${{secrets.APP_SECRET}}
          PAYPAL_MERCHANT_ID: ${{secrets.MERCHANT_ID}}
          BASE_URL: ${{secrets.BASE_URL}}